### ISSUE TITLE
Package for Debian

### ISSUE THREAD

**Issue by lofidevops** [EFForg/cryptolog#3]
**User story:** I am a syadmin on a Debian-based system. I want to install a cryptolog as a Debian package, so that system integration and updates are handled by Debian maintainers.

**Suggested solution:** [RFP 894090](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=894090)

**Comment by FedericoCeratto** [comment]
cryptolog received 35 commits since 2011 and there are no releases on GitHub. Having some releases would help. Also documenting the security aspects of cryptolog and how the project will be maintained in future helps.

**Comment by Mikaela** [comment]
Porting it to Python 3 wouldn't hurt either with Python 2 being EOL.
